image: lgutter/codam_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

simple-test:
  stage: test
  before_script:
    - meson --version
    - ninja --version
    - meson build -Db_coverage=true
    - ninja -C build
  script:
    - build/test-cetushell
  after_script:
    - ninja -C build coverage --verbose
  artifacts:
    when: always
    paths:
      - build/meson-logs/
