image: lgutter/codam_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

simple-test:
  stage: test
  before_script:
    - meson --version
    - ninja --version
    - meson build -Db_coverage=true
    - ninja -C build
  script:
    - ninja test -C build
  after_script:
    - rm -rfv $(find . -regex ".*\.spec\.c\.gc[ndo][oav]")
    - ninja -C build coverage --verbose
    - mv build/meson-logs meson-logs
  artifacts:
    when: always
    paths:
      - meson-logs/
