image: lgutter/codam_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

gcc-test:
  stage: test
  before_script:
    - export HIST_PERM_TEST="true"
    - mkdir tmp
    - touch tmp/.test_read_acc
    - chmod 0222 tmp/.test_read_acc
    - touch tmp/.test_write_acc &&
    - chmod 0444 tmp/.test_write_acc
    - meson --version
    - ninja --version
    - meson build -Db_coverage=true
  script:
    - ninja test -C build --verbose
  after_script:
    - rm -rfv $(find . -regex ".*\.spec\.c\.gc[ndo][oav]")
    - ninja -C build coverage --verbose
    - mv build/meson-logs meson-logs
  artifacts:
    when: always
    paths:
      - meson-logs/

clang-test:
  stage: test
  before_script:
    - meson --version
    - ninja --version
    - CC=clang meson build
  script:
    - ninja test -C build --verbose
